// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// csr_sort_indices_inplace
void csr_sort_indices_inplace(IntegerVector& Ap, IntegerVector& Aj, NumericVector& Ax);
RcppExport SEXP _ACTIONetExperiment_csr_sort_indices_inplace(SEXP ApSEXP, SEXP AjSEXP, SEXP AxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type Ap(ApSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type Aj(AjSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Ax(AxSEXP);
    csr_sort_indices_inplace(Ap, Aj, Ax);
    return R_NilValue;
END_RCPP
}
// csc_sort_indices_inplace
void csc_sort_indices_inplace(IntegerVector& Ap, IntegerVector& Ai, NumericVector& Ax);
RcppExport SEXP _ACTIONetExperiment_csc_sort_indices_inplace(SEXP ApSEXP, SEXP AiSEXP, SEXP AxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type Ap(ApSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type Ai(AiSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type Ax(AxSEXP);
    csc_sort_indices_inplace(Ap, Ai, Ax);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ACTIONetExperiment_csr_sort_indices_inplace", (DL_FUNC) &_ACTIONetExperiment_csr_sort_indices_inplace, 3},
    {"_ACTIONetExperiment_csc_sort_indices_inplace", (DL_FUNC) &_ACTIONetExperiment_csc_sort_indices_inplace, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ACTIONetExperiment(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
