# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_var <- function(X) {
    .Call(`_ACTIONetExperiment_roll_var`, X)
}

fast_row_sums <- function(A) {
    .Call(`_ACTIONetExperiment_fast_row_sums`, A)
}

fast_column_sums <- function(A) {
    .Call(`_ACTIONetExperiment_fast_column_sums`, A)
}

fast_row_max <- function(A) {
    .Call(`_ACTIONetExperiment_fast_row_max`, A)
}

computeSparseRowVariances <- function(j, val, rm, n) {
    .Call(`_ACTIONetExperiment_computeSparseRowVariances`, j, val, rm, n)
}

bind_sparse_mats <- function(A, B, dim = 0L) {
    .Call(`_ACTIONetExperiment_bind_sparse_mats`, A, B, dim)
}

csr_sort_indices_inplace <- function(Ap, Aj, Ax) {
    invisible(.Call(`_ACTIONetExperiment_csr_sort_indices_inplace`, Ap, Aj, Ax))
}

csc_sort_indices_inplace <- function(Ap, Ai, Ax) {
    invisible(.Call(`_ACTIONetExperiment_csc_sort_indices_inplace`, Ap, Ai, Ax))
}

